spring:
  application:
    name: Imooc-Passbook
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/passbook?autoReconnect=true
    name: famgy
    password: abcd
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4
  data:
    hbase:
      quorum: 127.0.0.1:2181
      rootDir: file:///home/famgy/Bd/Hbase
      nodeParent: /hbase

  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 8080

logging:
  level: debug
  file: imooc-passbook.log

